app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::resource('categorias','CategoriasController');
Route::resource('clientes','ClientesController');
Route::resource('diarios_producto','Diarios_productosController');
Route::resource('diarios','DiariosController');
Route::resource('productos','ProductosController');
Route::resource('reservas','ReservasController');
Route::resource('servicios','ServiciosController');
Route::resource('trabajadores','TrabajadoresController');
Route::resource('trabajos','TrabajosController');
Route::resource('ventas','VentasController');

Route::get('reservas/confirmar/{id}',
	['as' 	=> 'reservas.confirmar',
		'uses' => 'ReservasController@confirmar']);

Route::get('reportes/ticket/{id}',
	['as' 	=>'reportes.ticket',
		'uses' => 'ReportesController@ticket']);

Route::get('reportes/operador',
	['as' 	=>'reportes.operador',
		'uses' => 'ReportesController@operador']);

Route::get('productos/vendido/{id}',
	['as'	=>'productos.vendido',
		'uses' => 'ProductosController@vendido']);

Route::get('reportes/diario',
	['as' 	=>'reportes.diario',
		'uses' => 'ReportesController@diario']);

Route::get('reservas/{id}/destroy',[
    'uses' => 'ReservasController@destroy',
    'as' => 'reservas.destroy']);

app/Reserva.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Reserva extends Model
{
    protected $table = "reservas";

    protected $fillable = ['nombre','apellido','celular','fecha', 'hora' ,'detalle','estado'];

     public function servicio()
    {
    	return $this->hasOne('App\Servicio','id','id_servicio');
    }
}

app/Http/Controllers/ReservasController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\Http\Requests;
use App\Servicio;
use App\Reserva;
use Laracasts\Flash\Flash;
use App\Trabajo;

use Illuminate\Support\Facades\DB;
use Carbon\Carbon;
use App\Trabajador;

class ReservasController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */

    public function __construct()
    {
        \Carbon\Carbon::setLocale('es');
    }
    
    public function index()
    {
        //
        $reservas= Reserva::all();
        $servicios = Servicio::lists('nombre','id');
        return view('reservas.index')->with('servicios',$servicios)->with('reservas',$reservas);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
        //dd($request);
        $reserva = new Reserva();
        $reserva->nombre= $request->nombre;
        $reserva->apellido = $request->apellido;
        $reserva->celular = $request->celular;
        $reserva->fecha = $request->fecha;
        $reserva->hora = $request->hora;
        $reserva->detalle = $request->detalle;
        $reserva->estado = 'pendiente';
        $reserva->id_servicio = $request->servicio;

        $reserva->save();

        Flash::success("Se ha realizado la reserva de forma exitosa!");

        return redirect()->route('reservas.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $reserva = Reserva::find($id);
        $servicios = Servicio::lists('nombre','id');
        return view('reservas.edit')->with('reserva',$reserva)->with('servicios',$servicios);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //dd($request->all());
        $reserva = Reserva::find($id);
        $reserva->nombre = $request->nombre;
        $reserva->apellido = $request->apellido;
        $reserva->celular = $request->celular;
        $reserva->fecha = $request->fecha;
        $reserva->hora = $request->hora;
        $reserva->detalle = $request->detalle;
        $reserva->id_servicio = $request->servicio;

        $reserva->save();
        Flash::success("Se ha modificado la reserva de forma exitosa!");

        return redirect()->route('reservas.index');

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $reserva= Reserva::find($id);
        $reserva->delete();
        flash("Se ha eliminado la reserva", 'danger')->important();

    return redirect()->route('reservas.index');
    }

    public function confirmar($id)
    {
       
        $ultimo = Trabajo::select('numero','fecha')->orderBy('id','DSC')->first();

        $fecha = $ultimo->fecha;
        if ( \Carbon\Carbon::now()->format('m') > \Carbon\Carbon::parse($ultimo->fecha)->format('m')) {
            $print = 1;

        }
        else{
              
              $print = (($ultimo->numero)+1);
        }
        
        $largo = str_pad($print,4,'0',STR_PAD_LEFT);
        $reserva = Reserva::find($id);
        $servicios = Servicio::lists('nombre','id');
        $operador = Trabajador::lists('nombre','id');
        
        return view('reservas.confirmar')->with('servicios',$servicios)->with('reserva',$reserva)->with('ultimo',$ultimo)->with('largo',$largo)->with('operador',$operador)->with('print',$print);
    }
    
    
}

resources/views/reservas/confirmar.blade.php
@extends('templates.blank')

@section('content')
<script src="{{asset('assets/js/jquery.min.js')}}"></script>
<script type="text/javascript">
    $(document).ready(function(){

            $("#prueba").click(function(){
                /*$("#formulario").hide();
                $("#loading").show(3000);
                $("#loading").hide(2000);
               setTimeout("$('#imprimir_ticket')[0].click()",5000);*/

            });
       $("#trabajo").submit(function(){
            $("#formulario").hide();
            $("#loading").show(3000);
            $("#loading").hide(3000);
            $('#imprimir_ticket')[0].click();
        });
        
        $("#guardar").click(function(){
             $(".error").remove();
                if ($("#nombre").val() == "" ) {
                    $("#nombre").focus().after(" <span class='error'>Completa este Campo </span>");
                    return false;   
                }
                else if ($("#apellido").val() == "" ) {
                    $("#apellido").focus().after(" <span class='error'>Completa este Campo </span>");
                    return false;   
                }
                else if ($("#celular").val() == "" ) {
                    $("#celular").focus().after(" <span class='error'>Completa este Campo </span>");
                    return false;   
                }
                else if ($("#servicio").val() == "" ) {
                    $("#servicio").focus().after(" <span class='error'>Completa este Campo </span>");
                    return false;   
                }
                else if ($("#fecha").val() == "" ) {
                    $("#fecha").focus().after(" <span class='error'>Completa este Campo </span>");
                    return false;   
                }
                else if ($("#hora").val() == "" ) {
                    $("#hora").focus().after(" <span class='error'>Completa este Campo </span>");
                    return false;   
                }
                else if ($("#operador").val() == "" ) {
                    $("#operador").focus().after(" <span class='error'>Completa este Campo </span>");
                    return false;   
                }
                else{
                    
                    //var u=$('#suj_pa').attr('action');
                    //var d=$('#suj_pa').serialize()
                    $.ajax({
                    
                    type: $('#trabajo').attr('method'),
                    url: $('#trabajo').attr('action'),
                    data: $('#trabajo').serialize(),
                    success: function (data){
                        
                        $("#formulario").hide();
                        $("#loading").show(3000);
                        $("#loading").hide(3000);
                        setTimeout("$('#imprimir_ticket')[0].click()",2000);
                        
                        setTimeout("location.href= '../../trabajos'",3000);

                        ;}
                    
                    
                     });
                };
        })
        
            
        
    });
</script>

<h3 align="center">Confirmar reserva</h3>
<div class="row">
    <div id="loading" align="center" hidden=""><img src="{{asset('/assets/images/tenor.gif')}}" width="200">
</div>
<div id="formulario">
{!!Form::open(array('action'=>'TrabajosController@store','method'=>'POST','id'=>'trabajo','class'=>'form-horizontal')) !!}
         <div class="form-group">
            {!!Form::label('Nombre','Nombre cliente:',['class'=>'col-sm-3 control-label no-padding-right'] ) !!}
            <div class="col-sm-9">
            {!!Form::text('nombre',$reserva->nombre,['class'=>'col-xs-10 col-sm-8', 'placeholder'=>'Ingrese el nombre','required','id'=>'nombre']) !!}
            </div>
        </div>
       <div class="form-group">
            {!!Form::label('Apellido','Apellido cliente:',['class'=>'col-sm-3 control-label no-padding-right'] ) !!}
            <div class="col-sm-9">
            {!!Form::text('apellido',$reserva->apellido,['class'=>'col-xs-10 col-sm-8', 'placeholder'=>'Ingrese el apellido','required','id'=>'apellido']) !!}
            </div>
        </div>
        <div class="form-group">
            {!!Form::label('Celular','Celular:',['class'=>'col-sm-3 control-label no-padding-right'] ) !!}
            <div class="col-sm-9">
            {!!Form::text('celular',$reserva->celular,['class'=>'col-xs-10 col-sm-8', 'placeholder'=>'Ingrese el celular','required','id'=>'celular']) !!}
            </div>
        </div>
        <div class="form-group">
            {!!Form::label('Servicio','Servicio:',['class'=>'col-sm-3 control-label no-padding-right'] ) !!}
            <div class="col-sm-9">
            {!!Form::select('servicio',$servicios,$reserva->id_servicio,['class'=>'col-xs-10 col-sm-8', 'placeholder'=>'Seleccione el servicio','required','id'=>'servicio']) !!}
            </div>
        </div>
         <div class="form-group">
            {!!Form::label('Fecha','Fecha:',['class'=>'col-sm-3 control-label no-padding-right'] ) !!}
            <div class="col-sm-9">
            {!!Form::text('fecha',$reserva->fecha,['class'=>'col-xs-10 col-sm-8', 'placeholder'=>'Ingrese el nombre','required','id'=>'txtfecha','id'=>'fecha']) !!}
            </div>
        </div>
        <div class="form-group">
            {!!Form::label('Hora','Hora:',['class'=>'col-sm-3 control-label no-padding-right'] ) !!}
            <div class="col-sm-9">
            {!!Form::time('hora',$reserva->hora,['class'=>'col-xs-10 col-sm-8', 'placeholder'=>'Ingrese el nombre','required','id'=>'hora']) !!}
            </div>
        </div>
        <div class="form-group">
            {!!Form::label('Servicio','Operador/a:',['class'=>'col-sm-3 control-label no-padding-right'] ) !!}
            <div class="col-sm-9">
            {!!Form::select('trabajador',$operador,null,['class'=>'col-xs-10 col-sm-8', 'placeholder'=>'Seleccione el operador','required','id'=>'operador']) !!}
            </div>
        </div>
        <div class="form-group">
            {!!Form::label('Detalle/','Detalle/Observaciones:',['class'=>'col-sm-3 control-label no-padding-right'] ) !!}
            <div class="col-sm-9">
            {!!Form::textarea('detalle',$reserva->detalle,['rows'=>'5', 'class'=>'col-xs-10 col-sm-8', 'placeholder'=>'Detalles','required']) !!}
            </div>
        </div>
         <div class="form-group">
            {!!Form::label('codigo','Codigo:',['class'=>'col-sm-3 control-label no-padding-right'] ) !!}
            <div class="col-sm-9">
            {!!Form::text('codigo',Date::now()->format('F').'-'.$largo,['class'=>'col-xs-10 col-sm-8','required','readonly']) !!}
            </div>
        </div>

        <div class="form-group">
            {!!Form::label('codigo','Codigo:',['class'=>'col-sm-3 control-label no-padding-right'] ) !!}
            <div class="col-sm-9">
            {!!Form::text('print',$print,['class'=>'col-xs-10 col-sm-8','required','readonly']) !!}
            </div>
        </div>
        <div class="form-footer" align="center">
        <a href="{{route('trabajos.index')}}" class="btn btn-danger" data-dismiss="modal">Cancelar</a> 
        
        <button type="button" class="btn btn-success" id="guardar">Guardar</button>
      </div>
        {!!Form::close() !!}	
</div>

<div  id="ticket" hidden="">  
<a href="{{ route('reportes.ticket',Date::now()->format('F').'-'.$largo) }}" target="_blank" class="btn btn-success btn-xs" id="imprimir_ticket">personal</a>
</div>

</div>

<button hidden="" id="prueba">prueba</button>



@endsection

resources/views/reservas/edit.blade.php
@extends('templates.blank')

@section('content')
<script src="{{asset('assets/js/jquery.min.js')}}"></script>


<h3 align="center">Editar Reserva</h3>
<div class="row">
   
<div id="formulario">
{!!Form::open(['route'=>['reservas.update',$reserva],'method'=>'PUT','class'=>'form-horizontal']) !!}
         <div class="form-group">
            {!!Form::label('Nombre','Nombre cliente:',['class'=>'col-sm-3 control-label no-padding-right'] ) !!}
            <div class="col-sm-9">
            {!!Form::text('nombre',$reserva->nombre,['class'=>'col-xs-10 col-sm-8', 'placeholder'=>'Ingrese el nombre','required','id'=>'nombre']) !!}
            </div>
        </div>
       <div class="form-group">
            {!!Form::label('Apellido','Apellido cliente:',['class'=>'col-sm-3 control-label no-padding-right'] ) !!}
            <div class="col-sm-9">
            {!!Form::text('apellido',$reserva->apellido,['class'=>'col-xs-10 col-sm-8', 'placeholder'=>'Ingrese el apellido','required','id'=>'apellido']) !!}
            </div>
        </div>
        <div class="form-group">
            {!!Form::label('Celular','Celular:',['class'=>'col-sm-3 control-label no-padding-right'] ) !!}
            <div class="col-sm-9">
            {!!Form::text('celular',$reserva->celular,['class'=>'col-xs-10 col-sm-8', 'placeholder'=>'Ingrese el celular','required','id'=>'celular']) !!}
            </div>
        </div>
        <div class="form-group">
            {!!Form::label('Servicio','Servicio:',['class'=>'col-sm-3 control-label no-padding-right'] ) !!}
            <div class="col-sm-9">
            {!!Form::select('servicio',$servicios,$reserva->id_servicio,['class'=>'col-xs-10 col-sm-8', 'placeholder'=>'Seleccione el servicio','required','id'=>'servicio']) !!}
            </div>
        </div>
         <div class="form-group">
            {!!Form::label('Fecha','Fecha:',['class'=>'col-sm-3 control-label no-padding-right'] ) !!}
            <div class="col-sm-9">
            {!!Form::date('fecha',$reserva->fecha,['class'=>'col-xs-10 col-sm-8', 'placeholder'=>'Ingrese el nombre','required','id'=>'txtfecha','id'=>'fecha']) !!}
            </div>
        </div>
        <div class="form-group">
            {!!Form::label('Hora','Hora:',['class'=>'col-sm-3 control-label no-padding-right'] ) !!}
            <div class="col-sm-9">
            {!!Form::time('hora',$reserva->hora,['class'=>'col-xs-10 col-sm-8', 'placeholder'=>'Ingrese el nombre','required','id'=>'hora']) !!}
            </div>
        </div>
        
        <div class="form-group">
            {!!Form::label('Detalle/','Detalle/Observaciones:',['class'=>'col-sm-3 control-label no-padding-right'] ) !!}
            <div class="col-sm-9">
            {!!Form::textarea('detalle',$reserva->detalle,['rows'=>'3', 'class'=>'col-xs-10 col-sm-8', 'placeholder'=>'Detalles']) !!}
            </div>
        </div>
         
        
        <div class="form-footer" align="center">
        <a href="{{route('reservas.index')}}" class="btn btn-danger" >Cancelar</a> 
        
        <button type="submit" class="btn btn-success" id="guardar">Guardar cambios</button>
      </div>

        {!!Form::close() !!}
</div>	





</div>

<button hidden="" id="prueba">prueba</button>


@endsection

resources/views/reservas/index.blade.php
@extends('templates.blank')

@section('content')

<div class="row">
	<div class="col"></div>
	<div class="col-7"><div id="calendario"></div> </div>
	<div class="col"></div>
</div>



<link rel="stylesheet" href="{{asset('assets/css/fullcalendar.css')}}">
<script src="{{asset('assets/js/jquery.min.js')}}"></script>
<script src="{{asset('assets/js/moment.min.js')}}"></script>
<script src="{{asset('assets/js/fullcalendar.js')}}"></script>


<script src="{{asset('assets/js/locale-all.js')}}"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>


<script>
	$(document).ready(function(){
        $("#btnModificar").click(function(){
            var id= $("#id").html();
            location.href = "reservas/"+id+"/edit";
            

        })
         $("#btnConfirmar").click(function(){
            var id= $("#id").html();
            location.href = "reservas/confirmar/"+id;
            

        })
         $("#btnEliminar").click(function(){
            var id = $("#id").html();
            $("#confirmar").modal();
         })

         $("#btnDelete").click(function(){
            var id= $("#id").html();
            //alert(id);
            location.href = "reservas/"+id+"/destroy";
         })
            

		$('#calendario').fullCalendar({
            height:600,
            minTime:{
                Duration:"08:00:00"
            },
            
            defaultView:'agendaWeek',
            slotLabelFormat: 'h:mm a',
            
           
			header:{
				left:'today,prev,next',
				center:'title',
				right:'month,agendaWeek,agendaDay'
			},

		dayClick:function(date,jsEvent,view){
				
				
                $("#txtfecha").val(date.format());
				$("#exampleModal").modal();
			},	
            eventSources:[{

                
                events:[
                
                @foreach($reservas as $res)
               
                {
                    title: '{{$res->nombre}}'+' '+'{{$res->apellido}}',
                    id: '{{$res->id}}',
                    servicio: '{{$res->servicio->nombre}}',
                    celular: '{{$res->celular}}',
                    detalle: '{{$res->detalle}}',
                    fecha: '{{$res->fecha}}'+' '+'{{$res->hora}}',
                    start: '{{$res->fecha}}'+' '+'{{$res->hora}}',
                    end: '{{$res->fecha}}'+' '+'{{$res->hora+1}}',
                    color: '{{$res->servicio->categoria->color}}',
                                             
                },
                @endforeach
                ],
                
                
            
                
            }],
			


        eventClick: function(calEvent,jsEvent,view){
            $("#id").html(calEvent.id);
            $("#servicio").html(calEvent.servicio);
            $("#title").html(calEvent.title);
            $("#celular").html(calEvent.celular);
            $("#start").html(calEvent.fecha);
            $("#detalle").html(calEvent.detalle);
            $("#mostrarModal").modal();
        }
              
		});

		
	});


</script>

<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Reserva E-lashes</h5>
        
      </div>
      <div class="modal-body">
        {!!Form::open(array('action'=>['ReservasController@store'],'method'=>'POST','id'=>'reserva','class'=>'form-horizontal')) !!}
        <div class="form-group">
        	{!!Form::label('Nombre','Nombre cliente:',['class'=>'col-sm-3 control-label no-padding-right'] ) !!}
        	<div class="col-sm-9">
        	{!!Form::text('nombre',null,['class'=>'col-xs-10 col-sm-8', 'placeholder'=>'Ingrese el nombre','required','id'=>'nombre']) !!}
        	</div>
        </div>
       <div class="form-group">
        	{!!Form::label('Apellido','Apellido cliente:',['class'=>'col-sm-3 control-label no-padding-right'] ) !!}
        	<div class="col-sm-9">
        	{!!Form::text('apellido',null,['class'=>'col-xs-10 col-sm-8', 'placeholder'=>'Ingrese el apellido','required','id'=>'apellido']) !!}
        	</div>
        </div>
        <div class="form-group">
        	{!!Form::label('Celular','Celular:',['class'=>'col-sm-3 control-label no-padding-right'] ) !!}
        	<div class="col-sm-9">
        	{!!Form::text('celular',null,['class'=>'col-xs-10 col-sm-8', 'placeholder'=>'Ingrese el celular','required']) !!}
        	</div>
        </div>
        <div class="form-group">
        	{!!Form::label('Servicio','Servicio:',['class'=>'col-sm-3 control-label no-padding-right'] ) !!}
        	<div class="col-sm-9">
        	{!!Form::select('servicio',$servicios,null,['class'=>'col-xs-10 col-sm-8', 'placeholder'=>'Seleccione el servicio','required']) !!}
        	</div>
        </div>
         <div class="form-group">
            {!!Form::label('Fecha','Fecha:',['class'=>'col-sm-3 control-label no-padding-right'] ) !!}
            <div class="col-sm-9">
            {!!Form::text('fecha',null,['class'=>'col-xs-10 col-sm-8', 'placeholder'=>'Ingrese el nombre','required','id'=>'txtfecha']) !!}
            </div>
        </div>
        <div class="form-group">
        	{!!Form::label('Hora','Hora:',['class'=>'col-sm-3 control-label no-padding-right'] ) !!}
        	<div class="col-sm-9">
        	{!!Form::time('hora',null,['class'=>'col-xs-10 col-sm-8', 'placeholder'=>'Ingrese el nombre','required']) !!}
        	</div>
        </div>
        <div class="form-group">
        	{!!Form::label('Detalle','Detalle:',['class'=>'col-sm-3 control-label no-padding-right'] ) !!}
        	<div class="col-sm-9">
        	{!!Form::textarea('detalle',null,['rows'=>'5', 'class'=>'col-xs-10 col-sm-8', 'placeholder'=>'Detalle de la reserva']) !!}
        	</div>
        </div>
        
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancelar</button>
        <button type="submit" class="btn btn-primary">Realizar reserva</button>
      </div>
      {!!Form::close() !!}


    </div>
  </div>
</div>

<!-- Modal mostrar-->
<div class="modal fade" id="mostrarModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <strong><h5 class="modal-title" id="servicio" align="center"></h5></strong><label id="id"></label>
        
      </div>
      <div class="modal-body">
        {!!Form::open(array('action'=>['ReservasController@index'],'method'=>'GET','id'=>'reserva','class'=>'form-horizontal')) !!}
        
        
        
       <div class="form-group">
            {!!Form::label('Nombre','Nombre cliente:',['class'=>'col-sm-3 control-label no-padding-right'] ) !!}
            <div class="col-sm-9">
            {!!Form::label('nombre',null,['class'=>'col-xs-10 col-sm-8','id'=>'title']) !!}
            </div>
        </div>
       
        <div class="form-group">
            {!!Form::label('Celular','Celular:',['class'=>'col-sm-3 control-label no-padding-right'] ) !!}
            <div class="col-sm-9">
            {!!Form::label('celular',null,['class'=>'col-xs-10 col-sm-8','id'=>'celular']) !!}
            </div>
        </div>
        
         <div class="form-group">
            {!!Form::label('Fecha','Fecha:',['class'=>'col-sm-3 control-label no-padding-right'] ) !!}
            <div class="col-sm-9">
            {!!Form::label('start',null,['class'=>'col-xs-10 col-sm-8','id'=>'start']) !!}
            </div>
        </div>
        
        <div class="form-group">
            {!!Form::label('Detalle','Detalle:',['class'=>'col-sm-3 control-label no-padding-right'] ) !!}
            <div class="col-sm-9">
            {!!Form::label('detalle',null,['class'=>'col-xs-10 col-sm-8','id'=>'detalle']) !!}
            </div>
        </div>
        
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-danger" id="btnEliminar"><i class="menu-icon fa fa-trash"></i>Eliminar</button>
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancelar</button>
        <button type="button" class="btn btn-primary" id="btnConfirmar">Confirmar</button>
         <button type="button" class="btn btn-success" id="btnModificar">Modificar</button>        
      </div>
      {!!Form::close() !!}


    </div>
  </div>
</div>

<div class="modal" tabindex="-1" role="dialog" id="confirmar">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Eliminar Reserva</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <p>Esta seguro que desea eliminar la reserva?</p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-danger" id="btnDelete">Eliminar</button>
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancelar</button>
      </div>
    </div>
  </div>
</div>

@endsection