app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::resource('categorias','CategoriasController');
Route::resource('clientes','ClientesController');
Route::resource('diarios_producto','Diarios_productosController');
Route::resource('diarios','DiariosController');
Route::resource('productos','ProductosController');
Route::resource('reservas','ReservasController');
Route::resource('servicios','ServiciosController');
Route::resource('trabajadores','TrabajadoresController');
Route::resource('trabajos','TrabajosController');
Route::resource('ventas','VentasController');

Route::get('reservas/confirmar/{id}',
	['as' 	=> 'reservas.confirmar',
		'uses' => 'ReservasController@confirmar']);

Route::get('reportes/ticket/{id}',
	['as' 	=>'reportes.ticket',
		'uses' => 'ReportesController@ticket']);

Route::get('reportes/operador',
	['as' 	=>'reportes.operador',
		'uses' => 'ReportesController@operador']);

Route::get('productos/vendido/{id}',
	['as'	=>'productos.vendido',
		'uses' => 'ProductosController@vendido']);

Route::get('reportes/diario',
	['as' 	=>'reportes.diario',
		'uses' => 'ReportesController@diario']);

Route::get('reservas/{id}/destroy',[
    'uses' => 'ReservasController@destroy',
    'as' => 'reservas.destroy']);

resources/views/operadores/create.blade.php
@extends('templates.blank')

@section('content')
<h3 align="center">Nuevo Operador E-lashes</h3>
<div class="row">
	{!!Form::open(['route'=>'trabajadores.store','method'=>'POST','class'=>'form-horizontal']) !!}
        <div class="form-group">
            {!!Form::label('Nombre','Nombre:',['class'=>'col-sm-3 control-label no-padding-right'] ) !!}
            <div class="col-sm-9">
            {!!Form::text('nombre',null,['class'=>'col-xs-10 col-sm-8', 'placeholder'=>'Ingrese el nombre','required']) !!}
            </div>
        </div>
        <div class="form-group">
            {!!Form::label('apellido','Apellido:',['class'=>'col-sm-3 control-label no-padding-right'] ) !!}
            <div class="col-sm-9">
            {!!Form::text('apellido',null,['class'=>'col-xs-10 col-sm-8', 'placeholder'=>'Ingrese el apellido','required']) !!}
            </div>
        </div>
        
       <div class="form-group">
            {!!Form::label('costo','C.I.:',['class'=>'col-sm-3 control-label no-padding-right'] ) !!}
            <div class="col-sm-9">
            {!!Form::text('ci',null,['class'=>'col-xs-10 col-sm-8', 'placeholder'=>'Ingrese el C.I.','required']) !!}
            </div>
        </div>
        <div class="form-group">
            {!!Form::label('cantidad','Celular:',['class'=>'col-sm-3 control-label no-padding-right'] ) !!}
            <div class="col-sm-9">
            {!!Form::text('celular',null,['class'=>'col-xs-10 col-sm-8', 'placeholder'=>'Ingrese el celular','required']) !!}
            </div>
        </div>
        <div class="form-group">
            {!!Form::label('cantidad','Direccion:',['class'=>'col-sm-3 control-label no-padding-right'] ) !!}
            <div class="col-sm-9">
            {!!Form::text('direccion',null,['class'=>'col-xs-10 col-sm-8', 'placeholder'=>'Ingrese la direccion','required']) !!}
            </div>
        </div>
        
        <div class="form-group" align="center">
            
            {!!Form::button('Cancelar',['class'=>'btn btn-danger']) !!}
            {!!Form::submit('Agregar operador',['class'=>'btn btn-success']) !!}
        </div>
        {!!Form::close() !!}
</div>




      
        
     
      
@endsection

resources/views/operadores/index.blade.php
@extends('templates.blank')

@section('content')
<h3 align="center">Operadores E-lashes</h3>
<div class="row">
	

    <table class="table table-light table-hover">
        <thead>
            <th>Nro</th>
            <th>Nombre</th>
            <th>Apellido</th>
            <th>C.I.</th>
            <th>Celular</th>
            <th>Direccion</th>
            <th>Accion</th>
            

        </thead>

        <tbody>
            <br>
            @foreach($operadores as $ser)
            <tr>

                <td>{{ $ser->id }}</td>
                <td>{{ $ser->nombre }}</td>
                <td>{{ $ser->apellido }}</td>
                <td>{{ $ser->ci }}</td>
                <td>{{ $ser->celular }}</td>
                <td>{{ $ser->direccion }}</td>
                
                <td><a href="{{ route('trabajadores.edit',$ser->id) }}" class="btn btn-xs btn-success ">Editar</a>
                <a href="{{ route('trabajadores.destroy',$ser->id) }}" class="btn btn-xs btn-success ">Eliminar</a></td>
                
            </tr>
            @endforeach


        </tbody>


    </table>
</div>




@endsection