app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::resource('categorias','CategoriasController');
Route::resource('clientes','ClientesController');
Route::resource('diarios_producto','Diarios_productosController');
Route::resource('diarios','DiariosController');
Route::resource('productos','ProductosController');
Route::resource('reservas','ReservasController');
Route::resource('servicios','ServiciosController');
Route::resource('trabajadores','TrabajadoresController');
Route::resource('trabajos','TrabajosController');
Route::resource('ventas','VentasController');

Route::get('reservas/confirmar/{id}',
	['as' 	=> 'reservas.confirmar',
		'uses' => 'ReservasController@confirmar']);

Route::get('reportes/ticket/{id}',
	['as' 	=>'reportes.ticket',
		'uses' => 'ReportesController@ticket']);

Route::get('reportes/operador',
	['as' 	=>'reportes.operador',
		'uses' => 'ReportesController@operador']);

Route::get('productos/vendido/{id}',
	['as'	=>'productos.vendido',
		'uses' => 'ProductosController@vendido']);

Route::get('reportes/diario',
	['as' 	=>'reportes.diario',
		'uses' => 'ReportesController@diario']);

Route::get('reservas/{id}/destroy',[
    'uses' => 'ReservasController@destroy',
    'as' => 'reservas.destroy']);

app/Servicio.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Servicio extends Model
{
    protected $table = "servicios";

    protected $fillable = ['nombre','costo','descripcion','descuento','id_categoria_servicio'];

    public function scopeBusqueda($query, $request)
    {
        
       // dd("scope: ",$busca);
        return $query->where('nombre','LIKE',"%".$request."%");
                     
    }
    public function categoria()
    {
    	return $this->hasOne('App\Categoria_servicio','id','id_categoria_servicio');
    }
}

app/Http/Controllers/ServiciosController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\Http\Requests;
use App\Servicio;
use Laracasts\Flash\Flash;
use App\Categoria_servicio;
use Jenssegers\Date\Date;

use Carbon\Carbon;

class ServiciosController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        //
        $servicio= Servicio::busqueda($request->busca)->orderBy('id','ASC')->paginate(10);
        //$servicio = Servicio::all();
        return view('servicios.index')->with('servicio',$servicio);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $categoria = Categoria_servicio::lists('nombre','id');
        return view('servicios.create')->with('categoria',$categoria);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $servicio = new Servicio($request->all());
        $servicio->save();

        Flash::success("Se ha registrado el nuevo servicio de forma exitosa");

        return redirect()->route('servicios.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/servicios/create.blade.php
@extends('templates.blank')

@section('content')
<h3 align="center">Nuevo Servicio E-lashes</h3>
<div class="row">
	{!!Form::open(['route'=>'servicios.store','method'=>'POST','id'=>'servicio','class'=>'form-horizontal']) !!}
        <div class="form-group">
            {!!Form::label('Nombre','Nombre:',['class'=>'col-sm-3 control-label no-padding-right'] ) !!}
            <div class="col-sm-9">
            {!!Form::text('nombre',null,['class'=>'col-xs-10 col-sm-8', 'placeholder'=>'Ingrese el nombre','required']) !!}
            </div>
        </div>
        <div class="form-group">
            {!!Form::label('Categoria','Categoria:',['class'=>'col-sm-3 control-label no-padding-right'] ) !!}
            <div class="col-sm-9">
            {!!Form::select('id_categoria_servicio',$categoria,null,['class'=>'col-xs-10 col-sm-8', 'placeholder'=>'Seleccione la categoria','required']) !!}
            </div>
        </div>
       <div class="form-group">
            {!!Form::label('costo','Precio:',['class'=>'col-sm-3 control-label no-padding-right'] ) !!}
            <div class="col-sm-9">
            {!!Form::text('costo',null,['class'=>'col-xs-10 col-sm-8', 'placeholder'=>'Ingrese el precio del servicio','required']) !!}
            </div>
        </div>
        <div class="form-group">
            {!!Form::label('descripcion','Descripcion:',['class'=>'col-sm-3 control-label no-padding-right'] ) !!}
            <div class="col-sm-9">
            {!!Form::text('descripcion',null,['class'=>'col-xs-10 col-sm-8', 'placeholder'=>'Ingrese la descripcion','required']) !!}
            </div>
        </div>
        
       
        <div class="form-group">
            {!!Form::label('descuento','Descuento:',['class'=>'col-sm-3 control-label no-padding-right'] ) !!}
            <div class="col-sm-9">
            {!!Form::text('descuento',null,[ 'class'=>'col-xs-10 col-sm-8', 'placeholder'=>'Ingrese el descuento del producto (opcional)']) !!}
            </div>
        </div>
        <div class="form-group" align="center">
            {!!Form::submit('Agregar servicio',['class'=>'btn btn-success']) !!}
            {!!Form::button('Cancelar',['class'=>'btn btn-danger']) !!}
        </div>
        {!!Form::close() !!}
</div>




      
        
     
      
@endsection

resources/views/servicios/index.blade.php
@extends('templates.blank')

@section('content')
<h3 align="center">Servicios E-lashes</h3>
<div class="row">
	
{!! Form::open(['route'=>'servicios.index','method'=>'GET', 'class'=>'form-search']) !!}
        <div class="input-group">
            <span class="input-group-addon">
                <i class="ace-icon fa fa-check"></i>
            </span>

            <input type="text" class="form-control search-query" name="busca" placeholder="Ingresa el servicio a buscar" />
                <span class="input-group-btn">
                <button type="submit" class="btn btn-inverse btn-white">
                <span class="ace-icon fa fa-search icon-on-right bigger-110"></span>
                Buscar
                </button>
                </span>
    </div>
{!!Form::close() !!}
    <table class="table table-light table-hover">
        <thead>
            <th>Cod</th>
            <th>Nombre</th>
            <th>Precio</th>
            <th>Descripcion</th>
            <th>Descuento</th>
            <th>Accion</th>
            

        </thead>

        <tbody>
            <br>
            @foreach($servicio as $ser)
            <tr>

                <td>{{ $ser->id }}</td>
                <td>{{ $ser->nombre }}</td>
                <td>{{ $ser->costo }}</td>
                <td>{{ $ser->descripcion }}</td>
                <td>{{ $ser->descuento }}</td>
                
                <td><a href="{{ route('servicios.edit',$ser->id) }}" class="btn btn-success btn-xs">Editar</a></td>
                
                 
    
            </tr>
            @endforeach


        </tbody>


    </table>
</div>


{{$servicio->links()}}

@endsection